version: '3.10'

services:
  database:
    container_name: mysql
    image: mysql
    command: ["--default-authentication-plugin=caching_sha2_password"]    
    ports:
      - 3306:3306
    volumes:
      - ./banco/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db_users
      MYSQL_USER: tux
      MYSQL_PASSWORD: ABC123xyz         
    networks:
      - app
    restart: always

  appy:
    container_name: app
    build: "./app"
    ports:
      - 8080:8080
    networks:
      - app
    restart: always

networks:
  app:
    driver: "bridge"
