version: '3.10'

services:
  database:
    container_name: mysql
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password", "--sql_mode="]    
    ports:
      - 3306:3306
    volumes:
      - ./banco/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: banco
      MYSQL_USER: tux
      MYSQL_PASSWORD: Mud@r123         
    networks:
      - app
    restart: always

  appy:
    container_name: python
    build: "./app"
    ports:
      - 5000:5000
    networks:
      - app
    restart: always

networks:
  app:
    driver: "bridge"